comands = {
    1: 'user_1 = User.objects.create_user(username = ''hunt'')',
    2: 'user_2 = User.objects.create_user(username = ''vega'')',
    3: 'author_1 = Author.objects.create(user = user_1)',
    4: 'author_2 = Author.objects.create(user = user_2)',
    5: 'Category.objects.create(name = ''спорт'')',
    6: 'Category.objects.create(name = "политика")',
    7: 'Category.objects.create(name = "эстрада")',
    8: 'Category.objects.create(name = "природа")',
    9: 'news_1 = Post.objects.create(author = author_1, state_news = ''NE'')',
    10: 'sport = Category.objects.get(name = "спорт")',
    11: 'teatr = Category.objects.get(name = "эстрада")',
    12: 'polit = Category.objects.get(name = "политика")',
    13: 'nature = Category.objects.get(name = "природа")',
    14: 'news_1.category.add(sport)',
    15: 'news_1.category.add(polit)',
    16: 'state_1 = Post.objects.create(author = author_2, state_news = "ST")',
    17: 'state_1.category.add(nature, polit)',
    18: 'state_2 = Post.objects.create(author = author_1, state_news = ''ST'')',
    19: 'state_2.category.add(teatr, nature)',
    20: 'comment_1 = Comment.objects.create(post = news_1, user = user_1, comment = "so cool")',
    21: 'comment_2 = Comment.objects.create(post = state_1, user = user_2, comment = "so cool and nicely")',
    22: 'comment_3 = Comment.objects.create(post = state_2, user = user_2, comment = "somnitelno no okey")',
    23: 'comment_4 = Comment.objects.create(post = state_1, user = user_1, comment = "niceeeeee")',
    24: 'comment_1.like()"4x"',
    25: 'comment_2.like()"3x"',
    26: 'comment_3.dislike()',
    27: 'comment_4.like(), comment_4.dislike()',
    28: 'author_1.update_rating()',
    29: 'author_2.update_rating()',
    30: 'Author.objects.all().order_by("-reit").values("user", "reit").first()',
    31: 'news_1.text = "какой нибудь текст"',
    32: 'news_1.hat = "random text"',
    33: 'state_1.text = "какой нибудь текст"',
    34: 'state_1.hat = "random text 1"',
    35: 'state_2.text = "какой нибудь текст"',
    36: 'state_2.hat = "random text 2"',
    37: 'Post.objects.all().order_by("-reit").values("time_in", "author", "reit", "hat", "preview")[0]',
    38: ' Comment.objects.get(post = news_1).values("time_in", "user", "reit", "comment")'
}